version: "2" # required to adjust maintainability checks
checks:
    # sonar suggests 15 as a good threshold
    method-complexity:
        config:
            threshold: 10
exclude_patterns:
    - "**/node_modules/"
    - "**/test/"
    - "**/seed-data"
