import { CardBuilder } from "../../helpers/seeder.js";

const data = {
	name: "",
	type: "buff",
	description: "",
	actionName: "buff",
	actionValue: 0,
	duration: 0,
	cost: 0,
	aoe: false,
	rarity: "common",
	pluralSubject: "",
	singularSubject: "",
};

export default {
	modelName: "Card",
	data: [
		new CardBuilder({
			...data,
			name: "Energy Boost",
			actionName: "energy",
			actionValue: 2,
			cost: 2,
			duration: 3,
		}),
		new CardBuilder({
			...data,
			name: "Damage Boost",
			actionName: "damage",
			actionValue: 2,
			cost: 2,
			duration: 3,
		}),
		new CardBuilder({
			...data,
			name: "Health Boost",
			actionName: "heal",
			actionValue: 2,
			cost: 2,
			duration: 3,
		}),
		new CardBuilder({
			...data,
			name: "Shield Boost",
			actionName: "shield",
			actionValue: 2,
			cost: 2,
			duration: 3,
		}),
		new CardBuilder({
			...data,
			name: "Energy Surge",
			actionName: "energy",
			actionValue: 7,
			cost: 2,
			duration: 3,
			rarity: "uncommon",
		}),
		new CardBuilder({
			...data,
			name: "Damage Surge",
			actionName: "damage",
			actionValue: 7,
			cost: 2,
			duration: 3,
			rarity: "uncommon",
		}),
		new CardBuilder({
			...data,
			name: "Health Surge",
			actionName: "heal",
			actionValue: 7,
			cost: 2,
			duration: 3,
			rarity: "uncommon",
		}),
		new CardBuilder({
			...data,
			name: "Shield Surge",
			actionName: "shield",
			actionValue: 7,
			cost: 2,
			duration: 3,
			rarity: "uncommon",
		}),
		new CardBuilder({
			...data,
			name: "Damage Flood",
			actionName: "damage",
			actionValue: 10,
			cost: 3,
			duration: 3,
			rarity: "rare",
		}),
		new CardBuilder({
			...data,
			name: "Shield Flood",
			actionName: "shield",
			actionValue: 10,
			cost: 3,
			duration: 3,
			rarity: "rare",
		}),
	],
};
